version: '3.9'

services:
  app:
    build: .
    container_name: syraa-prod-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./.env:/app/.env:ro
      - ./credentials.json:/app/credentials.json:ro
      - ./token.pickle:/app/token.pickle:ro
    ports:
      - "8000:8000"

volumes:
  pgdata: 